routes/web.php
<?php
use App\Product;
use App\Categorie;
use App\Support;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');

Route::get('/client', 'ClientController@index')->name('client');

Route::resource('product', 'ProductController')
    ->middleware('auth');
  
Route::resource('categorie', 'CategorieController');
Route::resource('support', 'SupportController');
Route::resource('SubCategorie', 'SubCategorieController');

Route::get('/user-home', 'UserHomeController@list')->name('user-home');

Auth::routes();

Route::get('/confirmation', function () {
    return view('auth.confirmation');
});

Route::get('/administrateur.dashboard', 'AdminController@login')->name('dashboard');

Route::get('/article/{id}', 'ArticleController@show')->name('article');

Route::post('/find',function(){
    $q = Input::get ( 'q' );
    // $categorySelect = Input::get('categorie');
    // $supportSelect = Input::get('supports');
    $product = Product::where('name','LIKE','%'.$q.'%')->get();
    if(count($product) > 0)
        return view('search')->withDetails($product)->withQuery ( $q );
    else return view ('search')->withMessage('No Details found. Try to search again !');
});

app/Sub_categorie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sub_categorie extends Model
{
    protected $fillable = ['id', 'name', 'categorie_id'];

     public function categorie()
    {
        return $this->belongsTo('App\Categorie', 'categorie_id');
    }
}

app/Http/Controllers/SubCategorieController.php
<?php

namespace App\Http\Controllers;

use App\Sub_categorie;
use Illuminate\Http\Request;


class SubCategorieController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sub_categories = Sub_categorie::with('subCategory')->get();
        return view('administrateur.subCategorie.page', compact('sub_categorie'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('administrateur.subCategorie.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'categorie_id'=>'required',
        ]);

        $sub_categorie = new Sub_categorie ([
            'name' => $request->get('name'),
            'categorie_id' => $request->get('categorie_id'),
        ]);
        $sub_categorie->save();
        return redirect('/SubCategorie')->with('success', 'Sub Categorie creer!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Sub_categorie  $sub_categorie
     * @return \Illuminate\Http\Response
     */
    public function show(Sub_categorie $sub_categorie)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Sub_categorie  $sub_categorie
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sub_categorie = Sub_categorie::findOrFail($id);
        return view('administrateur.subCategorie.edit')->withSubCategorie($sub_categorie);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Sub_categorie  $sub_categorie
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sub_categorie $sub_categorie)
    {
        $request->validate([
            'name'=>'required',
            'categorie_id'=>'required',
        ]);

        Sub_categorie::find($sub_categorie)->update($request->all());

        return redirect('/SubCategorie');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Sub_categorie  $sub_categorie
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sub_categorie $sub_categorie)
    {
        $sub_categorie->delete();

        return redirect('/SubCategorie')->with('success', 'Sub Categorie deleted!');
    }
}

resources/views/administrateur/subCategorie/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h1 class="display-3">Nouvelle Sub Categorie</h1>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif
                <form method="post" action="{{ route('SubCategorie.store') }}">
                    @csrf
                    <div class="form-group">
                        <label for="name">Sub Categorie:</label>
                        <input type="text" class="form-control" name="name"/>
                    </div>

                    <div class="form-group">
                        <label for="categorie_id">Categorie ID:</label>
                        <input type="text" class="form-control" name="categorie_id"/>
                    </div>

                    <button type="submit" class="btn btn-primary">Creer Sub Categorie</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/administrateur/subCategorie/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h1 class="display-3">Update Sub Categorie</h1>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                <br />
            @endif
            <form method="post" action="{{ route('SubCategorie.update', $subCategorie->id) }}">
                @method('PATCH')
                @csrf
                <div class="form-group">

                    <label for="name">Nom Categorie:</label>
                    <input type="text" class="form-control" name="name" value={{ $subCategorie->name }} />
                </div>

                <div class="form-group">
                    <label for="categorie_id">Categorie ID:</label>
                    <input type="text" class="form-control" name="categorie_id" value={{ $subCategorie->categorie_id
                    }} />
                </div>

                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
@endsection

resources/views/administrateur/subCategorie/page.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1 class="display-3">Sub Categories</h1>
            <table class="table table-striped">
                <thead>
                <tr>
                    <td>ID</td>
                    <td>Nom</td>
                    <td>Categorie ID</td>
                    <td colspan=2>Actions</td>
                </tr>
                </thead>
                <tbody>
                @foreach($sub_categories  as $sub_categorie)
                    <tr class="align-content-center">
                        <td class="align-middle">{{$sub_categorie->id}}</td>
                        <td class="align-middle">{{$sub_categorie->name}}</td>
                        <td class="align-middle">{{$sub_categorie->categorie_id}}</td>
                        <td class="align-middle">
                            <a href="{{ route('SubCategorie.create',$sub_categorie )}}" class="btn
                            btn-primary">Ajout</a>
                        </td>

                        <td class="align-middle">
                            <a href="{{ route('SubCategorie.edit', $sub_categorie )}}" class="btn
                            btn-warning">Edit</a>
                        </td>
                        <td class="align-middle">
                            <form action="{{ route('SubCategorie.destroy', $sub_categorie )}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Supprimer</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            </div>
    </div>
    </div>
@endsection