routes/web.php
<?php
use App\Product;
use App\Categorie;
use App\Support;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');

Route::get('/client', 'ClientController@index')->name('client');

Route::resource('product', 'ProductController')
    ->middleware('auth');
  
Route::resource('categorie', 'CategorieController');
Route::resource('support', 'SupportController');
Route::resource('SubCategorie', 'SubCategorieController');

Route::get('/user-home', 'UserHomeController@list')->name('user-home');

Auth::routes();

Route::get('/confirmation', function () {
    return view('auth.confirmation');
});

Route::get('/administrateur.dashboard', 'AdminController@login')->name('dashboard');

Route::get('/article/{id}', 'ArticleController@show')->name('article');

Route::post('/find',function(){
    $q = Input::get ( 'q' );
    // $categorySelect = Input::get('categorie');
    // $supportSelect = Input::get('supports');
    $product = Product::where('name','LIKE','%'.$q.'%')->get();
    if(count($product) > 0)
        return view('search')->withDetails($product)->withQuery ( $q );
    else return view ('search')->withMessage('No Details found. Try to search again !');
});

app/Support.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Support extends Model
{
    protected $fillable = ['id', 'name', 'support'];
}

app/Http/Controllers/SupportController.php
<?php

namespace App\Http\Controllers;

use App\Support;
use Illuminate\Http\Request;

class SupportController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $supports = Support::all();

        return view('administrateur.support.page', compact('supports'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('administrateur.support.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'support'=>'required',
        ]);

        $support = new support([
            'support' => $request->get('support'),
        ]);
        $support->save();
        return redirect('/support')->with('success', 'Support creer!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Support  $support
     * @return \Illuminate\Http\Response
     */
    public function show(Support $support)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Support  $support
     * @return \Illuminate\Http\Response
     */
    public function edit(Support $support)
    {
        $support = Support::findOrFail($id);
        return view('administrateur.support.edit')->withSupport($support);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Support  $support
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Support $support)
    {
        $request->validate([
            'support'=>'required',
        ]);

        Support::find($support)->update($request->all());

        return redirect('/support');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Support  $support
     * @return \Illuminate\Http\Response
     */
    public function destroy(Support $support)
    {
        $support->delete();

        return redirect('/support')->with('success', 'Support deleted!');
    }
}

resources/views/administrateur/support/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h1 class="display-3">Nouveau Support</h1>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif
                <form method="post" action="{{ route('support.store') }}">
                    @csrf
                    <div class="form-group">
                        <label for="support">Support:</label>
                        <input type="text" class="form-control" name="support"/>
                    </div>
                    <button type="submit" class="btn btn-primary">Nouveau Support</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/administrateur/support/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h1 class="display-3">Update Support</h1>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                <br />
            @endif
            <form method="post" action="{{ route('support.update', $support->id) }}">
                @method('PATCH')
                @csrf
                <div class="form-group">

                    <label for="support">Support:</label>
                    <input type="text" class="form-control" name="support" value={{ $support->support}} />
                </div>

                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
@endsection

resources/views/administrateur/support/page.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1 class="display-3">Supports</h1>
            <table class="table table-striped">
                <thead>
                <tr>
                    <td>ID</td>
                    <td>Support</td>
                    <td colspan=2>Actions</td>
                </tr>
                </thead>
                <tbody>
                @foreach($supports as $support)
                    <tr>
                        <td class="align-middle">{{$support->id}}</td>
                        <td class="align-middle">{{$support->support}}</td>
                        <td class="align-middle">
                            <a href="{{ route('support.create',$support )}}" class="btn btn-primary">Ajout</a>
                        </td>

                        <td class="align-middle">
                            <a href="{{ route('support.edit', $support )}}" class="btn
                            btn-warning">Edit</a>
                        </td>
                        <td class="align-middle">
                            <form action="{{ route('support.destroy', $support)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Supprimer</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            </div>
    </div>
    </div>
@endsection