routes/web.php
<?php
use App\Product;
use App\Categorie;
use App\Support;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');

Route::get('/client', 'ClientController@index')->name('client');

Route::resource('product', 'ProductController')
    ->middleware('auth');
  
Route::resource('categorie', 'CategorieController');
Route::resource('support', 'SupportController');
Route::resource('SubCategorie', 'SubCategorieController');

Route::get('/user-home', 'UserHomeController@list')->name('user-home');

Auth::routes();

Route::get('/confirmation', function () {
    return view('auth.confirmation');
});

Route::get('/administrateur.dashboard', 'AdminController@login')->name('dashboard');

Route::get('/article/{id}', 'ArticleController@show')->name('article');

Route::post('/find',function(){
    $q = Input::get ( 'q' );
    // $categorySelect = Input::get('categorie');
    // $supportSelect = Input::get('supports');
    $product = Product::where('name','LIKE','%'.$q.'%')->get();
    if(count($product) > 0)
        return view('search')->withDetails($product)->withQuery ( $q );
    else return view ('search')->withMessage('No Details found. Try to search again !');
});

app/Categorie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categorie extends Model
{
    protected $fillable = ['id', 'name', 'picture'];
    
}

app/Http/Controllers/CategorieController.php
<?php

namespace App\Http\Controllers;

use App\Categorie;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CategorieController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories= Categorie::all();
        return view('administrateur.categorie.page', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('administrateur.categorie.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'picture'=>'required',
        ]);

        $categorie = new categorie([
            'name' => $request->get('name'),
            'picture' => $request->get('picture'),
        ]);
        $categorie->save();
        return redirect('/categorie')->with('success', 'Categorie creer!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Categorie  $categorie
     * @return \Illuminate\Http\Response
     */
    public function show(Categorie $categorie)
    {
        $categories = Categorie::pluck('categorie_name', 'id');
        return view('pages.welcome') ->with('categories', $categories);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Categorie  $categorie
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categorie = Categorie::findOrFail($id);
        return view('administrateur.categorie.edit')->withCategorie($categorie);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Categorie  $categorie
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Categorie $categorie)
    {
        $request->validate([
            'name'=>'required',
            'picture'=>'required',
        ]);

        Categorie::find($categorie)->update($request->all());

        return redirect('/categorie');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Categorie  $categorie
     * @return \Illuminate\Http\Response
     */
    public function destroy(Categorie $categorie)
    {
        $categorie->delete();

        return redirect('/categorie')->with('success', 'Categorie deleted!');
    }
}

resources/views/administrateur/categorie/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h1 class="display-3">Nouvelle categorie</h1>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif
                <form method="post" action="{{ route('categorie.store') }}">
                    @csrf
                    <div class="form-group">
                        <label for="name">Nom Categorie:</label>
                        <input type="text" class="form-control" name="name"/>
                    </div>

                    <div class="form-group">
                        <label for="picture">Image Url:</label>
                        <input type="text" class="form-control" name="picture"/>
                    </div>

                    <button type="submit" class="btn btn-primary">Nouvelle Categorie</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/administrateur/categorie/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h1 class="display-3">Update Categorie</h1>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                <br />
            @endif
            <form method="post" action="{{ route('categorie.update', $categorie->id) }}">
                @method('PATCH')
                @csrf
                <div class="form-group">

                    <label for="name">Nom Categorie:</label>
                    <input type="text" class="form-control" name="name" value={{ $categorie->name }} />
                </div>

                <div class="form-group">
                    <label for="picture">Image Url:</label>
                    <input type="text" class="form-control" name="picture" value={{ $categorie->picture }} />
                </div>

                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
@endsection

resources/views/administrateur/categorie/page.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1 class="display-3">Categories</h1>
            <table class="table table-striped">
                <thead>
                <tr>
                    <td>ID</td>
                    <td>Nom</td>
                    <td>Image</td>
                    <td colspan=2>Actions</td>
                </tr>
                </thead>
                <tbody>
                @foreach($categories as $categorie)
                    <tr class="align-content-center">
                        <td class="align-middle">{{$categorie->id}}</td>
                        <td class="align-middle">{{$categorie->name}}</td>
{{--                        <td>{{$categorie->picture}}</td>--}}
                        <td class="align-middle"><img src="{{$categorie->picture}}" class="img-thumbnail" width="150px"
                                 alt="image-responsive"></td>

                        <td class="align-middle">
                            <a href="{{ route('categorie.create',$categorie )}}" class="btn btn-primary">Ajout</a>
                        </td>

                        <td class="align-middle">
                            <a href="{{ route('categorie.edit', $categorie )}}" class="btn
                            btn-warning">Edit</a>
                        </td>
                        <td class="align-middle">
                            <form action="{{ route('categorie.destroy', $categorie)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Supprimer</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            </div>
    </div>
    </div>
@endsection