routes/web.php
<?php
use App\Product;
use App\Categorie;
use App\Support;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');

Route::get('/client', 'ClientController@index')->name('client');

Route::resource('product', 'ProductController')
    ->middleware('auth');
  
Route::resource('categorie', 'CategorieController');
Route::resource('support', 'SupportController');
Route::resource('SubCategorie', 'SubCategorieController');

Route::get('/user-home', 'UserHomeController@list')->name('user-home');

Auth::routes();

Route::get('/confirmation', function () {
    return view('auth.confirmation');
});

Route::get('/administrateur.dashboard', 'AdminController@login')->name('dashboard');

Route::get('/article/{id}', 'ArticleController@show')->name('article');

Route::post('/find',function(){
    $q = Input::get ( 'q' );
    // $categorySelect = Input::get('categorie');
    // $supportSelect = Input::get('supports');
    $product = Product::where('name','LIKE','%'.$q.'%')->get();
    if(count($product) > 0)
        return view('search')->withDetails($product)->withQuery ( $q );
    else return view ('search')->withMessage('No Details found. Try to search again !');
});

resources/views/produits/create.blade.php
@extends('layouts.app')
@include('includes.Head')
@include('includes.Header')
@section('content')
{{-- <h3 class="userNameTitle">Bienvenue<h3> --}}
    <div class="row formCreate">
        <div class="col-sm-8 offset-sm-2">
            <h1 class="display-3 titreFormCrate">Déposer une annonce</h1>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif
                <form method="POST" action="{{ route('product.store') }}">
                    @csrf
                    <div class="form-group">
                        <label for="name">Nom produit</label>
                        <input type="text" class="form-control" name="name"/>
                    </div>

                    <div class="form-group">
                        {{Form::label('categories_id', 'Categories')}}
                        <select class="form-control" name="categories_id">
                            @foreach($categories as $categorie)
                                <option value='{{$categorie->id}}'>{{$categorie->name}}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        {{Form::label('subcategories_id', 'Sub Categories')}}
                        <select class="form-control" name="sub_categorie_id">
                            @foreach($sub_categories as $sub_categorie)
                                <option value='{{$sub_categorie->id}}'>{{$sub_categorie->name}}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        {{Form::label('supports_id', 'Supports')}}
                        <select class="form-control" name="support_id">
                            @foreach($supports as $support)
                                <option value='{{$support->id}}'>{{$support->support}}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="description">Description:</label>
                        <textarea name="description" class="form-control"></textarea>
                    </div>

                    {{-- <div class="form-group">
                        <label for="picture">Image</label>
                        <input type="file" class="form-control imageImput" name="picture"/>
                    </div> --}}
                    
                        @csrf
                        <input type="file" name="picture">
                        <button type="submit" class="btn btn-primary btnAjout">Ajouter</button>
                </form>
            </div>
        </div>
    </div>
    @include('includes.Footer')
@endsection

resources/views/produits/view.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <h1 class="display-3">Liste de produits</h1>
            <table class="table table-striped">
                <thead>
                <tr>
                    <td>ID</td>
                    <td>Nom du produit</td>
                    <td>Categorie</td>
                    <td>Sub categorie</td>
                    <td>Support</td>
                    <td>Description</td>
                    <td>Image</td>
                    <td colspan = 2>Actions</td>
                </tr>
                </thead>
                <tbody>
                @foreach($products as $product)
                    <tr>
                        <td>{{$product->id}}</td>
                        <td>{{$product->name}}</td>
                        <td>{{$product->subCategory->categorie->name}}</td>
                        <td>{{$product->subCategory->name}}</td>
                        <td>{{$product->support->support}}</td>
                        <td>{{$product->description}}</td>
                        <td>{{$product->user->name}}</td>
                        <td>
                            <a href="{{ route('product.edit',$product->id)}}" class="btn btn-primary">Edit</a>
                        </td>
                        <td>
                            <form action="{{ route('product.destroy', $product->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            </div>
            </div>

@endsection